export * from './parser-variable'
export * from './parser-import'
export * from './parser-vbind-m'
export { parserCompiledSfc } from './parser-compiled-sfc'
export { analyzeScriptBindings as parseScriptBindings } from './parser-script-bindings'
export type { IParseSFCRes } from './parser-compiled-sfc'
