export * from './parser-variable'
export * from './parser-import'
export * from './parser-vbindm'
export { parserCompiledSfc } from './parser-compiled-sfc'
export type { IParseSFCRes } from './parser-compiled-sfc'
